//
//  AssetIcon.swift
//  Ziyon
//
//  Created by Elioene Fernandes on 02/07/23.
//

#if os(iOS)
import NotificationCenter
#endif
public enum AssetIcon: String, CaseIterable {
    case none = ""
    case analytics = "ziyon-analytics"
    case baby = "ziyon-baby"
    case bag = "ziyon-bag"
    case bars = "ziyon-bars"
    case calculator = "ziyon-calculator"
    case calendarArrow = "ziyon-calendar-arrow"
    case calendarData = "ziyon-calendar-data"
    case calendarEmpty = "ziyon-calendar-empty"
    case calendarLess = "ziyon-calendar-less"
    case calendarNo = "ziyon-calendar-no"
    case calendarPlus = "ziyon-calendar-plus"
    case calendarYes = "ziyon-calendar-yes"
    case calendar = "ziyon-calendar"
    case car = "ziyon-car"
    case card = "ziyon-card"
    case chatFill = "ziyon-chat-fill"
    case clothes = "ziyon-clothes"
    case chat = "ziyon-chat"
    case check = "ziyon-check"
    case chip = "ziyon-chip"
    case choice = "ziyon-choice"
    case cosmetics = "ziyon-cosmetics"
    case construction = "ziyon-construction"
    case crown = "ziyon-crown"
    case crownFill = "ziyon-crown-fill"
    case crypto = "ziyon-crypto"
    case company = "ziyon-company"
    case drag = "ziyon-drag"
    case edit = "ziyon-edit"
    case envelope = "ziyon-envelope"
    case erase = "ziyon-erase"
    case exchange = "ziyon-exchange"
    case food = "ziyon-food"
    case funds = "ziyon-funds"
    case gym = "ziyon-gym"
    case health = "ziyon-health"
    case homeFill = "ziyon-home-fill"
    case home = "ziyon-home"
    case park = "ziyon-park"
    case playWhiteFill = "ziyon-play-white-fill"
    case scrip = "ziyon-scrip"
    case shareWhite = "ziyon-share-white"
    case share = "ziyon-share"
    case shareArrow = "ziyon-share-arrow"
    case shopping = "ziyon-shopping"
    case tax = "ziyon-tax"
    case ticket = "ziyon-ticket"
    case time = "ziyon-time"
    case trash = "ziyon-trash"
    case trashSmall = "ziyon-trash-small"
    case wallet = "ziyon-wallet"
    case cloud = "ziyon-cloud"
    case discord = "ziyon-discord"
    case email = "ziyon-email"
    case permissions = "ziyon-permissions"
    case phone = "ziyon-phone"
    case policy = "ziyon-policy"
    case security = "ziyon-security"
    case user = "ziyon-user"
    case arrowRightLarge = "ziyon-arrow-right-large"
    case arrowRightMedium = "ziyon-arrow-right-medium"
    case arrowRightSmall = "ziyon-arrow-right-small"
    case arrowRight = "ziyon-arrow-right"
    case arrowThinRight = "ziyon-arrow-thin-right"
    case arrowDown = "ziyon-arrow-down"
    case arrowRechargeCircle = "ziyon-recharge-circle"
    case chevronDown = "ziyon-chevron-down"
    case chevronBackward = "ziyon-chevron-backward"
    case chevronForward = "ziyon-chevron-forward"
    case chevronUp = "ziyon-chevron-up"
    case chevronRightSmall = "ziyon-small-right-arrow"
    case alertSuccessCircle = "ziyon-alert-success-circle"
    case alertErrorCircle = "ziyon-alert-error-circle"
    case alertInfoCircle = "ziyon-alert-info-circle"
    case checkmark = "ziyon-checkmark"
    case errorCircle = "ziyon-error-circle"
    case xmarkLarge = "ziyon-xmark-large"
    case xmarkSmall = "ziyon-xmark-small"
    case xmark = "ziyon-xmark"
    case infoCircleSmall = "ziyon-info-circle-small"
    case minusFill = "ziyon-minus-fill"
    case minus = "ziyon-minus"
    case percentage = "ziyon-percentage"
    case plusFill = "ziyon-plus-fill"
    case plus = "ziyon-plus"
    case question = "ziyon-question"
    case success = "ziyon-success"
    case triangleExclamantion = "ziyon-triangle-exclamation"
    case update = "ziyon-update"
    case warningLarge = "ziyon-warning-large"
    case xmarkCircle = "ziyon-xmark-circle"
    case woman = "ziyon-woman"
    case pigbankplant = "pigbankplant"
    case palette = "ziyon-palette"
    case pigbank = "pigbank"
    case pet = "ziyon-pet"
    case mastercardLogo = "Mastercard-Logo"
    case macdesk = "macdesk"
    case learnMoney = "img-learn-money"
    case learnBasic = "img-learn-basic"
    case creditcard = "img-creditcard"
    case brand = "brand"
    case checked = "ziyon-checked"
    case unchecked = "ziyon-unchecked"
    case warning = "ziyon-warning"
    case rocket = "img-rocket"
    case coinBar = "ziyon-coin-bar"
    case coinCommunity = "ziyon-coin-community"
    case coinLogo = "ziyon-coin-logo"
    case coinTransfer = "ziyon-coin-transfer"
    case coinWorld = "ziyon-coin-world"
    // - Coins
    case coinZiyon = "ziyon"
    case coinYuan = "yuan"
    case coinYen = "yen"
    case coinWon = "won"
    case coinTether = "usdt"
    case coinRuble = "ruble"
    case coinBrazilian = "brl"
    case coinPound = "gbp"
    case coinEuro = "eur"
    case coinEthereum = "eth"
    case coinDollar = "usd"
    case coinBitcoin = "btc"
    case coinBinance = "bnb"
    case gold = "ziyon-gold"
    case document = "ziyon-document"
    case filter = "ziyon-filter"
    case settingsUser = "ziyon-user-fill-dash"
    case settingsPhone = "ziyon-phone-rear-camera"
    case settingsPermissions = "ziyon-gear"
    case settingsSecurity = "ziyon-security-lock"
    case settingsDataShare = "ziyon-security-exclamation"
    case safari = "ziyon-safari"
    case shoes = "ziyon-shoes"
    case shoppingfill = "ziyon-shopping-fill"
    case wifiSlash = "wifi.slash"
    case category = "ziyon-category"
    case client = "ziyon-client"
    case cardfill = "ic-card"
    case null = "ziyon-null"
    case expenseShoes = "ziyon-expense-shoes"
    case expenseShopping = "ziyon-expense-shopping"
    case expenseClient = "ziyon-espense-client"
    case expenseBaby = "ziyon-expense-baby"
    case expenseCardFill = "ziyon-expense-card-fill"
    case expenseClothes = "ziyon-expense-clothes"
    case expenseConstruction = "ziyon-expense-construction"
    case expenseCosmetics = "ziyon-expense-cosmetics"
    case expenseLaze = "ziyon-expense-laze"
    case expensePet = "ziyon-expense-pet"
    case ziyonKid = "ziyon-kid"
    case closingIndicator = "ziyon-closing-indicator"
    case speaker = "ziyon-speaker-circle"
    case calculatorBold = "ziyon-home-calculator"
    
#if os(iOS)
    public var forNotification: UNNotificationActionIcon {
        .init(templateImageName: self.rawValue)
    }
#endif
}
